package ca.csf.mobile2.tp2.question

import android.annotation.SuppressLint
import android.content.Intent
import android.view.View
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.widget.Toolbar
import ca.csf.mobile2.tp2.R
import kotlinx.android.synthetic.main.activity_ask_question.*
import org.androidannotations.annotations.*

@SuppressLint("Registered") //Reason : Generated by Android Annotations
@OptionsMenu(R.menu.activity_ask_question)
@EActivity(R.layout.activity_ask_question)
class AskQuestionActivity : AppCompatActivity() {

    @ViewById(R.id.toolbar)
    protected lateinit var toolbar: Toolbar

    @Bean
    protected lateinit var questionService: QuestionService

    @AfterViews
    protected fun onCreate() {
        initView()
        questionService.findRandomQuestion(this::onSuccess,this::onServerError,this::onConnectivityError)
    }

    @Click(R.id.choice1Button)
    protected fun onClickChoice1Button(){
        answerView.visibility = View.GONE
    }

    @Click(R.id.choice2Button)
    protected fun onClickChoice2Button(){
        answerView.visibility = View.GONE
    }

    private fun initView() {
        setSupportActionBar(toolbar)
    }

    private fun onSuccess (question : QuestionData){
        TODO()
    }

    private fun onServerError(){
        TODO()
    }

    private fun onConnectivityError(){
        TODO()
    }

    @OptionsItem(R.id.flagButton)
    protected fun flag() {
        TODO("Flag question")
    }

    @Click(R.id.createButton)
    protected fun onClickCreateQuestion(){
        startActivity(Intent(this,CreateQuestionActivity_::class.java))
    }
}

