package ca.csf.mobile2.tp2.question

import android.annotation.SuppressLint
import androidx.appcompat.app.AppCompatActivity
import ca.csf.mobile2.tp2.R
import org.androidannotations.annotations.EActivity

@SuppressLint("Registered") //Reason : Generated by Android Annotations
@EActivity(R.layout.activity_create_question)
class CreateQuestionActivity : AppCompatActivity()