package ca.csf.mobile2.tp2.question

import android.annotation.SuppressLint
import androidx.appcompat.app.AppCompatActivity
import ca.csf.mobile2.tp2.R
import com.google.android.material.textfield.TextInputLayout
import org.androidannotations.annotations.*
import java.util.*

@SuppressLint("Registered") //Reason : Generated by Android Annotations
@EActivity(R.layout.activity_create_question)
class CreateQuestionActivity : AppCompatActivity(){
    @Bean
    protected lateinit var questionService: QuestionService

    @ViewById(R.id.titleTextInputLayout)
    protected lateinit var titleTextInputLayout : TextInputLayout

    @ViewById(R.id.choice1TextInputLayout)
    protected lateinit var choice1TextInputLayout : TextInputLayout

    @ViewById(R.id.choice2TextInputLayout)
    protected lateinit var choice2TextInputLayout : TextInputLayout

    @AfterViews
    protected fun afterViews() {

    }

    @Click(R.id.createButton)
    protected fun createQuestion(){
        val questionData = createQuestionData()
        questionService.createQuestion(questionData,this::onSuccess,this::onServerError,this::onConnectivityError)
    }

    private fun createQuestionData() : QuestionData{
        return QuestionData(
            choice1TextInputLayout.editText?.text.toString(),
            choice2TextInputLayout.editText?.text.toString(),
            UUID.randomUUID(),
            0,
            0,
            titleTextInputLayout.editText?.text.toString()
        )
    }

    private fun onSuccess (question : QuestionData){
        TODO()
    }

    private fun onServerError(){
        TODO()

    }

    private fun onConnectivityError(){
        TODO()

    }
}